//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalCWEntities : DbContext
    {
        public CarRentalCWEntities()
            : base("name=CarRentalCWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAMOCHODY> SAMOCHODY { get; set; }
        public virtual DbSet<MODELE> MODELE { get; set; }
        public virtual DbSet<RODZAJE_PALIWA> RODZAJE_PALIWA { get; set; }
        public virtual DbSet<WYPOZYCZALNIE> WYPOZYCZALNIE { get; set; }
        public virtual DbSet<PAKIETY> PAKIETY { get; set; }
        public virtual DbSet<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual DbSet<HISTORIA_ZAMOWIENIA> HISTORIA_ZAMOWIENIA { get; set; }
        public virtual DbSet<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
