//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_ZAMOWIENIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORIA_ZAMOWIENIA()
        {
            this.ZAMOWIENIA1 = new HashSet<ZAMOWIENIA>();
        }
    
        public decimal ID_HISTORIA { get; set; }
        public Nullable<decimal> ID_PRAC { get; set; }
        public Nullable<decimal> ID_ZAMOWIENIE { get; set; }
        public decimal ID_KLIENT { get; set; }
        public Nullable<System.DateTime> DATA_WYDANIE { get; set; }
        public Nullable<System.DateTime> DATA_PRZYJECIE { get; set; }
        public bool TANKOWANIE { get; set; }
        public decimal ILOSC_TANKOWANIE { get; set; }
        public decimal KOSZT_TANKOWANIE { get; set; }
        public bool KOLIZJA { get; set; }
        public Nullable<System.DateTime> DATA_KOLIZJA { get; set; }
        public Nullable<decimal> KARA_KOLIZJA { get; set; }
    
        public virtual ZAMOWIENIA ZAMOWIENIA { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA1 { get; set; }
    }
}
