//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTA_PRACOWNIKOW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTA_PRACOWNIKOW()
        {
            this.PRACOWNICY1 = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_KON_PRACOWNIK { get; set; }
        public decimal ID_ROLA { get; set; }
        public decimal ID_PRAC { get; set; }
        public string NAZWA_PRACOWNIK { get; set; }
        public string HASLO_PRACOWNIK { get; set; }
    
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual ROLE ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRACOWNICY> PRACOWNICY1 { get; set; }
    }
}
