//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELE()
        {
            this.SAMOCHODY = new HashSet<SAMOCHODY>();
        }
    
        public decimal ID_MODEL { get; set; }
        public decimal ID_MARKA { get; set; }
        public decimal ID_NADWOZIE { get; set; }
        public string NAZWA_MODEL { get; set; }
        public string ROCZNIK { get; set; }
        public string GENERACJA { get; set; }
        public string SEGMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAMOCHODY> SAMOCHODY { get; set; }
    }
}
