//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMOCHODY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAMOCHODY()
        {
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public decimal ID_SAMOCHOD { get; set; }
        public decimal ID_PALIWO { get; set; }
        public decimal ID_MODEL { get; set; }
        public decimal ID_WYPOZYCZALNIA { get; set; }
        public byte[] ZDJECIE { get; set; }
        public string KOLOR { get; set; }
        public decimal PRZEBIEG { get; set; }
        public string VIN { get; set; }
        public decimal POJEMNOSC { get; set; }
        public decimal MOC { get; set; }
        public string SKRZYNIA { get; set; }
        public decimal MIEJSCA { get; set; }
        public decimal CENA_DZIEN { get; set; }
        public Nullable<decimal> CENA_TYDZIEN { get; set; }
        public Nullable<decimal> CENA_MIESIAC { get; set; }
        public Nullable<decimal> KAUCJA { get; set; }
    
        public virtual MODELE MODELE { get; set; }
        public virtual RODZAJE_PALIWA RODZAJE_PALIWA { get; set; }
        public virtual WYPOZYCZALNIE WYPOZYCZALNIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
