SELECT ID_SAMOCHOD, VIN, PRZEBIEG, NAZWA_MODEL 
FROM SAMOCHODY
JOIN MODELE ON SAMOCHODY.ID_MODEL = MODELE.iD_MODEL;

SELECT ID_SAMOCHOD, VIN, PRZEBIEG, MODELE.ID_MODEL, NAZWA_MODEL, NAZWA_NADWOZIE
FROM SAMOCHODY
JOIN MODELE ON SAMOCHODY.ID_MODEL = MODELE.ID_MODEL
JOIN RODZAJE_NADWOZIA ON MODELE.ID_NADWOZIE = RODZAJE_NADWOZIA.ID_NADWOZIE
WHERE NAZWA_NADWOZIE LIKE 'SUV';

SELECT ID_SAMOCHOD, VIN, PRZEBIEG, MODELE.ID_MODEL, NAZWA_MODEL, KRAJ, REGION
FROM SAMOCHODY
JOIN MODELE ON SAMOCHODY.ID_MODEL = MODELE.ID_MODEL
JOIN MARKI ON MODELE.ID_MARKA = MARKI.ID_MARKA
WHERE REGION LIKE 'Europa';

SELECT ID_ZAMOWIENIE, LICZBA_DNI, CENA_ZAMOWIENIE, NAZWA_MODEL, NAZWA_NADWOZIE FROM ZAMOWIENIA
JOIN SAMOCHODY ON ZAMOWIENIA.ID_SAMOCHOD = SAMOCHODY.ID_SAMOCHOD
JOIN MODELE ON SAMOCHODY.ID_MODEL = MODELE.ID_MODEL
JOIN RODZAJE_NADWOZIA ON MODELE.ID_NADWOZIE = RODZAJE_NADWOZIA.ID_NADWOZIE
JOIN PAKIETY ON ZAMOWIENIA.ID_PAKIET = PAKIETY.ID_PAKIET
WHERE ZAMOWIENIA.ID_PAKIET IS NOT NULL;

SELECT ZAMOWIENIA.ID_ZAMOWIENIE, NAZWA_MODEL, NAZWA_NADWOZIE, LICZBA_DNI, CENA_ZAMOWIENIE, CENA AS CENA_PAKIETU, DATA_START AS ROZPOCZECIE, DATA_KONIEC AS ZAKONCZENIE, DATA_WYDANIE AS WYDANIE, DATA_PRZYJECIE AS PRZYJECIE, DATA_KOLIZJA AS KOLIZJA, KARA_KOLIZJA FROM ZAMOWIENIA
JOIN SAMOCHODY ON ZAMOWIENIA.ID_SAMOCHOD = SAMOCHODY.ID_SAMOCHOD
JOIN RODZAJE_PALIWA ON SAMOCHODY.ID_PALIWO = RODZAJE_PALIWA.ID_PALIWO
JOIN MODELE ON SAMOCHODY.ID_MODEL = MODELE.ID_MODEL
JOIN RODZAJE_NADWOZIA ON MODELE.ID_NADWOZIE = RODZAJE_NADWOZIA.ID_NADWOZIE
JOIN PAKIETY ON ZAMOWIENIA.ID_PAKIET = PAKIETY.ID_PAKIET
JOIN HISTORIA_ZAMOWIENIA ON ZAMOWIENIA.ID_HISTORIA = HISTORIA_ZAMOWIENIA.ID_HISTORIA
WHERE KOLIZJA = 1 AND NAZWA_RODZAJ LIKE 'BENZYNA';